<?php
// Set up data for the layout
$page_title = 'Quản lý lịch chiếu';
$page_breadcrumb = 'Lịch chiếu rạp';
$show_clock = false;

// Additional CSS for this view
$additional_css = array('css/qlylich-calendar.css');

// Additional JavaScript
$additional_js = array(
    'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js'
);

// Sidebar sẽ tự động lấy menu dựa trên role (admin/staff)

// Start output buffering to capture content
ob_start();
?>

<div class="container-fluid">
    <div class="row">
        <!-- Calendar Section -->
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
                    <h4 class="mb-0">
                        <i class="fas fa-calendar-alt"></i> Lịch Chiếu Rạp
                    </h4>
                    <div class="btn-group">
                        <button class="btn btn-light btn-sm" id="prevMonth">
                            <i class="fas fa-chevron-left"></i>
                        </button>
                        <button class="btn btn-light btn-sm" id="todayBtn">Hôm nay</button>
                        <button class="btn btn-light btn-sm" id="nextMonth">
                            <i class="fas fa-chevron-right"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="calendar-header text-center mb-4">
                        <h3 id="calendarTitle" class="mb-0"></h3>
                    </div>

                    <div class="calendar-container">
                        <div class="calendar-grid">
                            <!-- Calendar days will be generated by JavaScript -->
                        </div>

                        <!-- Calendar Legend -->
                        <div class="calendar-legend mt-3">
                            <div class="legend-item">
                                <div class="legend-color available"></div>
                                <span>Không có lịch</span>
                            </div>
                            <div class="legend-item">
                                <div class="legend-color booked"></div>
                                <span>Có lịch chiếu</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Schedule Details Section -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <h5 class="mb-0">
                        <i class="fas fa-info-circle"></i> Chi Tiết Lịch Chiếu
                    </h5>
                </div>
                <div class="card-body">
                    <div id="scheduleDetails">
                        <div class="text-center text-muted">
                            <i class="fas fa-calendar-day fa-3x mb-3"></i>
                            <p>Chọn một ngày để xem chi tiết lịch chiếu</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Quick Actions -->
            <div class="card mt-3">
                <div class="card-header bg-success text-white">
                    <h6 class="mb-0">
                        <i class="fas fa-plus-circle"></i> Thao Tác
                    </h6>
                </div>
                <div class="card-body">
                    <button class="btn btn-success btn-sm mb-2 w-100" id="addScheduleBtn">
                        <i class="fas fa-plus"></i> Thêm Lịch Chiếu
                    </button>
                    <!-- <button class="btn btn-primary btn-sm mb-2 w-100" onclick="window.location.href='<?php echo base_url(); ?>index.php/Nhanvien_controller'">
                        <i class="fas fa-film"></i> Quản Lý Phim -->
                    </button>
                    <button class="btn btn-info btn-sm w-100" onclick="location.reload()">
                        <i class="fas fa-sync"></i> Làm Mới
                    </button>
                </div>
            </div>

            <!-- Statistics -->
            <div class="card mt-3">
                <div class="card-header bg-info text-white">
                    <h6 class="mb-0">
                        <i class="fas fa-chart-bar"></i> Thống Kê
                    </h6>
                </div>
                <div class="card-body">
                    <div class="row text-center">
                        <div class="col-6">
                            <div class="h4 mb-0 text-primary" id="totalSchedules">0</div>
                            <small class="text-muted">Tổng suất chiếu</small>
                        </div>
                        <div class="col-6">
                            <div class="h4 mb-0 text-success" id="activeMovies">0</div>
                            <small class="text-muted">Phim đang chiếu</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal for Schedule Details -->
<div class="modal fade" id="scheduleModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="scheduleModalTitle">Chi Tiết Lịch Chiếu</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="scheduleModalBody">
                <!-- Schedule details will be loaded here -->
            </div>
        </div>
    </div>
</div>

<!-- Modal for Add/Edit Schedule -->
<div class="modal fade" id="addScheduleModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Thêm Lịch Chiếu</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="scheduleForm">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="scheduleDate" class="form-label">Ngày Chiếu</label>
                                <input type="date" class="form-control" id="scheduleDate" required>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="scheduleMovie" class="form-label">Phim</label>
                                <select class="form-control" id="scheduleMovie" required>
                                    <option value="">Chọn phim...</option>
                                    <!-- Movies will be loaded here -->
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="scheduleRoom" class="form-label">Phòng Chiếu</label>
                                <select class="form-control" id="scheduleRoom" required>
                                    <option value="">Chọn phòng...</option>
                                    <option value="1">Phòng 1</option>
                                    <option value="2">Phòng 2</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                        <label for="scheduleTime" class="form-label">Giờ Chiếu (24h)</label>
                        <div class="d-flex">
                            <select id="scheduleHour" class="form-control" required style="max-width:110px; margin-right:8px;">
                                <option value="">Giờ</option>
                                <?php for ($h = 0; $h < 24; $h++): $hh = str_pad($h,2,'0',STR_PAD_LEFT); ?>
                                    <option value="<?php echo $hh; ?>"><?php echo $hh; ?></option>
                                <?php endfor; ?>
                            </select>
                            <select id="scheduleMinute" class="form-control" required style="max-width:110px;">
                                <option value="00">:00</option>
                                <option value="15">:15</option>
                                <option value="30">:30</option>
                                <option value="45">:45</option>
                            </select>
                        </div>
                            </div>
                        </div>
                    </div>

                    <input type="hidden" id="editingId" value="">
                    <div class="text-end">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Hủy</button>
                        <button type="submit" class="btn btn-primary">Lưu Lịch Chiếu</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
// Ensure Bootstrap is available
if (typeof bootstrap === 'undefined') {
    document.write('<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"><\/script>');
}

// Wait for jQuery to be loaded
function initCalendar() {
    console.log('Initializing Calendar...');

    let currentDate = new Date();
    // Currently selected date in calendar (YYYY-MM-DD) or null
    let selectedDate = null;
    let scheduleData = <?php echo json_encode($all_schedules); ?>;

    console.log('Schedule data loaded:', scheduleData);

    // Generate calendar
    function generateCalendar(date) {
        const year = date.getFullYear();
        const month = date.getMonth();

        // Update title
        const monthNames = ['Tháng 1', 'Tháng 2', 'Tháng 3', 'Tháng 4', 'Tháng 5', 'Tháng 6',
                           'Tháng 7', 'Tháng 8', 'Tháng 9', 'Tháng 10', 'Tháng 11', 'Tháng 12'];
        const calendarTitle = document.getElementById('calendarTitle');
        if (calendarTitle) {
            calendarTitle.textContent = `${monthNames[month]} ${year}`;
        }

        // Get first day of month and last day
        const firstDay = new Date(year, month, 1);
        const lastDay = new Date(year, month + 1, 0);
        const startDate = new Date(firstDay);
        startDate.setDate(startDate.getDate() - firstDay.getDay()); // Start from Sunday

        const calendarGrid = document.querySelector('.calendar-grid');
        if (!calendarGrid) {
            console.error('Calendar grid element not found');
            return;
        }
        calendarGrid.innerHTML = '';

        // Add day headers
        const dayNames = ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'];
        dayNames.forEach(dayName => {
            const dayHeader = document.createElement('div');
            dayHeader.className = 'calendar-day-header';
            dayHeader.textContent = dayName;
            calendarGrid.appendChild(dayHeader);
        });

        // Generate calendar days
        let currentDay = new Date(startDate);
        for (let i = 0; i < 42; i++) { // 6 weeks * 7 days
            const dayElement = document.createElement('div');
            dayElement.className = 'calendar-day';

            const dayNumber = currentDay.getDate();
            const isCurrentMonth = currentDay.getMonth() === month;

            // Local date string for this cell
            const dateStr = currentDay.getFullYear() + '-' +
                String(currentDay.getMonth() + 1).padStart(2, '0') + '-' +
                String(currentDay.getDate()).padStart(2, '0');
            dayElement.setAttribute('data-date', dateStr);

            if (isCurrentMonth) {
                dayElement.classList.add('current-month');
            } else {
                dayElement.classList.add('other-month');
            }

            dayElement.innerHTML = `<div class="day-number">${dayNumber}</div>`;

            // Check if this day has schedules
            const daySchedules = scheduleData.filter(schedule => schedule.day === dateStr);
            if (daySchedules.length > 0) {
                dayElement.classList.add('has-schedule');

                // Group schedules by room
                const room1Schedules = daySchedules.filter(s => s.id_phong == 1);
                const room2Schedules = daySchedules.filter(s => s.id_phong == 2);

                let scheduleHtml = '<div class="day-schedules">';

                if (room1Schedules.length > 0) {
                    scheduleHtml += `<div class="room-schedule room-1">${room1Schedules.length} suất P1</div>`;
                }

                if (room2Schedules.length > 0) {
                    scheduleHtml += `<div class="room-schedule room-2">${room2Schedules.length} suất P2</div>`;
                }

                scheduleHtml += '</div>';
                dayElement.innerHTML += scheduleHtml;
            }

            // If this day is the currently selected date, mark it
            if (selectedDate && dateStr === selectedDate) {
                dayElement.classList.add('selected');
            }

            // Add click handler for current-month days - select the day and show details
            if (isCurrentMonth) {
                dayElement.addEventListener('click', function() {
                    // Remove selected class from other days
                    const previouslySelected = document.querySelectorAll('.calendar-day.selected');
                    previouslySelected.forEach(el => el.classList.remove('selected'));
                    // Mark this as selected
                    this.classList.add('selected');
                    selectedDate = dateStr;
                    showScheduleDetails(dateStr);
                });
            }

            calendarGrid.appendChild(dayElement);
            currentDay.setDate(currentDay.getDate() + 1);
        }
    }

    // Show schedule details for a specific date
    function showScheduleDetails(dateStr) {
        console.log('Showing schedule details for:', dateStr);

        const scheduleDetails = document.getElementById('scheduleDetails');
        // Store the current date being viewed
        scheduleDetails.setAttribute('data-current-date', dateStr);

        scheduleDetails.innerHTML = '<div class="text-center"><i class="fas fa-spinner fa-spin"></i> Đang tải...</div>';

        // AJAX call to get schedule details
        $.ajax({
            url: '<?php echo base_url(); ?>index.php/Qlylich_controller/ajax_get_schedule_details/' + dateStr,
            type: 'GET',
            dataType: 'json',
            success: function(response) {
                console.log('Schedule details response:', response);

                if (response.success && response.schedules.length > 0) {
                    let html = `<h6 class="mb-3">Lịch chiếu ngày ${formatDate(dateStr)}</h6>`;

                    // Group by room
                    const room1Schedules = response.schedules.filter(s => s.id_phong == 1);
                    const room2Schedules = response.schedules.filter(s => s.id_phong == 2);

                    if (room1Schedules.length > 0) {
                        html += '<div class="mb-3">';
                        html += '<h6 class="text-primary">🏠 Phòng 1</h6>';
                        room1Schedules.forEach(schedule => {
                            html += createScheduleItem(schedule);
                        });
                        html += '</div>';
                    }

                    if (room2Schedules.length > 0) {
                        html += '<div class="mb-3">';
                        html += '<h6 class="text-primary">🏠 Phòng 2</h6>';
                        room2Schedules.forEach(schedule => {
                            html += createScheduleItem(schedule);
                        });
                        html += '</div>';
                    }

                    scheduleDetails.innerHTML = html;
                } else {
                    scheduleDetails.innerHTML = `
                        <div class="text-center text-muted">
                            <i class="fas fa-calendar-times fa-3x mb-3"></i>
                            <p>Không có lịch chiếu nào trong ngày ${formatDate(dateStr)}</p>
                        </div>
                    `;
                }
            },
            error: function(xhr, status, error) {
                console.error('Error loading schedule details:', error);
                scheduleDetails.innerHTML = `
                    <div class="text-center text-danger">
                        <i class="fas fa-exclamation-triangle fa-3x mb-3"></i>
                        <p>Không thể tải thông tin lịch chiếu</p>
                    </div>
                `;
            }
        });
    }

    function createScheduleItem(schedule) {
        return `
            <div class="schedule-item border rounded p-2 mb-2" data-id="${schedule.id_calendar}" data-day="${schedule.day}" data-time="${schedule.time}" data-id_movie="${schedule.id_movie}" data-id_phong="${schedule.id_phong}">
                <div class="d-flex justify-content-between align-items-start">
                    <div class="flex-grow-1">
                        <strong>${schedule.time} - ${schedule.end_time || 'N/A'}</strong>
                        <div class="small text-muted">
                            ${schedule.movie_title || 'Phim không xác định'}
                        </div>
                        ${schedule.movie_duration ? `<div class="small">${schedule.movie_duration}</div>` : ''}
                    </div>
                    <div class="btn-group btn-group-xs">
                        <button class="btn btn-warning btn-xs" onclick="editSchedule(this)">
                            <i class="fas fa-edit"></i>
                        </button>
                        <button class="btn btn-danger btn-xs" onclick="deleteSchedule(this)">
                            <i class="fas fa-trash"></i>
                        </button>
                    </div>
                </div>
            </div>
        `;
    }

    function formatDate(dateStr) {
        const date = new Date(dateStr);
        return date.toLocaleDateString('vi-VN', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
    }

    // Navigation handlers
    document.getElementById('prevMonth').addEventListener('click', () => {
        currentDate.setMonth(currentDate.getMonth() - 1);
        generateCalendar(currentDate);
    });

    document.getElementById('nextMonth').addEventListener('click', () => {
        currentDate.setMonth(currentDate.getMonth() + 1);
        generateCalendar(currentDate);
    });

    document.getElementById('todayBtn').addEventListener('click', () => {
        currentDate = new Date();
        generateCalendar(currentDate);

        // Select today's date in the calendar and show its details
        const todayDate = new Date();
        const todayStr = todayDate.getFullYear() + '-' +
            String(todayDate.getMonth() + 1).padStart(2, '0') + '-' +
            String(todayDate.getDate()).padStart(2, '0');

        // Update selected state
        selectedDate = todayStr;
        document.querySelectorAll('.calendar-day.selected').forEach(el => el.classList.remove('selected'));
        const todayEl = document.querySelector('.calendar-day[data-date="' + todayStr + '"]');
        if (todayEl) {
            todayEl.classList.add('selected');
        }

        showScheduleDetails(todayStr);
    });

    // Initialize calendar
    generateCalendar(currentDate);

    // Update statistics
    updateStatistics();

    // Event handlers
    setupEventHandlers();

    function updateStatistics() {
        const totalSchedules = scheduleData.length;
        const activeMovies = [...new Set(scheduleData.map(s => s.id_movie))].length;

        document.getElementById('totalSchedules').textContent = totalSchedules;
        document.getElementById('activeMovies').textContent = activeMovies;
    }

    function refreshCalendarData(callback) {
        console.log('Refreshing calendar data...');

        // Show loading overlay instead of replacing content
        const calendarContainer = document.querySelector('.calendar-container');
        let loadingOverlay = calendarContainer.querySelector('.loading-overlay');

        if (!loadingOverlay) {
            loadingOverlay = document.createElement('div');
            loadingOverlay.className = 'loading-overlay';
            loadingOverlay.style.cssText = `
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                background: rgba(255, 255, 255, 0.8);
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                z-index: 10;
                border-radius: 0.375rem;
            `;
            loadingOverlay.innerHTML = '<i class="fas fa-spinner fa-spin fa-2x text-primary"></i><br><small class="text-muted mt-2">Đang cập nhật lịch chiếu...</small>';

            // Make calendar container relative for absolute positioning
            calendarContainer.style.position = 'relative';
            calendarContainer.appendChild(loadingOverlay);
        }

        // Fetch updated schedule data from server
        $.ajax({
            url: '<?php echo base_url(); ?>index.php/Qlylich_controller/ajax_get_all_schedules',
            type: 'GET',
            dataType: 'json',
            success: function(response) {
                console.log('Updated schedule data:', response);
                if (response.success && response.schedules) {
                    scheduleData = response.schedules;
                    // Re-render calendar with new data
                    generateCalendar(currentDate);
                    // Update statistics
                    updateStatistics();
                    console.log('Calendar refreshed successfully');

                    // Remove loading overlay
                    if (loadingOverlay && loadingOverlay.parentNode) {
                        loadingOverlay.remove();
                    }

                    // Execute callback if provided
                    if (typeof callback === 'function') {
                        callback();
                    }
                } else {
                    console.error('Failed to refresh calendar data');
                    // Remove loading overlay and show error
                    if (loadingOverlay && loadingOverlay.parentNode) {
                        loadingOverlay.remove();
                    }
                    showErrorMessage('Không thể cập nhật dữ liệu lịch chiếu');
                }
            },
            error: function(xhr, status, error) {
                console.error('Error refreshing calendar:', error);
                // Remove loading overlay and show error
                if (loadingOverlay && loadingOverlay.parentNode) {
                    loadingOverlay.remove();
                }
                showErrorMessage('Lỗi kết nối khi cập nhật lịch chiếu');
                // Fallback to full reload if AJAX fails
                setTimeout(function() {
                    location.reload();
                }, 2000); // Give user time to see the error message
            }
        });
    }

    function setupEventHandlers() {
        // Add Schedule Button
        document.getElementById('addScheduleBtn').addEventListener('click', function() {
            console.log('Add schedule button clicked');
            openAddScheduleModal();
        });

        // Form submission
        document.getElementById('scheduleForm').addEventListener('submit', function(e) {
            e.preventDefault();
            saveSchedule();
        });
    }

    function openAddScheduleModal() {
        // Reset form
        document.getElementById('scheduleForm').reset();

        // Set default date to today
        // Use local date string to avoid timezone shifts causing off-by-one day.
        // If a calendar day was selected, use it; otherwise use today.
        const todayDate = new Date();
        const today = todayDate.getFullYear() + '-' +
            String(todayDate.getMonth() + 1).padStart(2, '0') + '-' +
            String(todayDate.getDate()).padStart(2, '0');
        const defaultDate = (typeof selectedDate === 'string' && selectedDate) ? selectedDate : today;
        document.getElementById('scheduleDate').value = defaultDate;

        // Set default time selects to current hour and :00
        try {
            const now = new Date();
            const curH = String(now.getHours()).padStart(2, '0');
            const curM = '00';
            const hourEl = document.getElementById('scheduleHour');
            const minuteEl = document.getElementById('scheduleMinute');
            if (hourEl) hourEl.value = curH;
            if (minuteEl) minuteEl.value = curM;
        } catch (e) {
            console.warn('Could not set default time selects', e);
        }

        // Load movies for dropdown
        loadMovies();

        // Show modal
        const modal = new bootstrap.Modal(document.getElementById('addScheduleModal'));
        modal.show();
    }

    function loadMovies() {
        // AJAX call to get movies
        // Accept optional callback by checking arguments
        var callback = null;
        if (arguments && arguments.length > 0 && typeof arguments[0] === 'function') {
            callback = arguments[0];
        }

        $.ajax({
            url: '<?php echo base_url(); ?>index.php/Qlylich_controller/ajax_get_movies',
            type: 'GET',
            dataType: 'json',
            success: function(response) {
                console.log('Movies loaded:', response);
                const movieSelect = document.getElementById('scheduleMovie');
                movieSelect.innerHTML = '<option value="">Chọn phim...</option>';

                if (response.success && response.movies) {
                    response.movies.forEach(function(movie) {
                        const option = document.createElement('option');
                        option.value = movie.id;
                        option.textContent = movie.title;
                        movieSelect.appendChild(option);
                    });
                }
                if (typeof callback === 'function') {
                    callback();
                }
            },
            error: function(xhr, status, error) {
                console.error('Error loading movies:', error);
            }
        });
    }

    function saveSchedule() {
        // Build time string from hour/minute selects (24h)
        const hourEl = document.getElementById('scheduleHour');
        const minuteEl = document.getElementById('scheduleMinute');
        const selectedHour = hourEl ? hourEl.value : '';
        const selectedMinute = minuteEl ? minuteEl.value : '';
        const timeStr = (selectedHour && selectedMinute) ? selectedHour + ':' + selectedMinute : '';

        const formData = {
            id_movie: document.getElementById('scheduleMovie').value,
            day: document.getElementById('scheduleDate').value,
            id_phong: document.getElementById('scheduleRoom').value,
            time: timeStr
        };

        console.log('Saving schedule:', formData);

        // Validate
        if (!formData.id_movie || !formData.day || !formData.id_phong || !formData.time) {
            showErrorMessage('Vui lòng điền đầy đủ thông tin!');
            return;
        }

        // Disable the save button and show loading state
        const saveBtn = document.querySelector('#scheduleForm button[type="submit"]');
        const originalText = saveBtn.innerHTML;
        saveBtn.disabled = true;
        saveBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Đang lưu...';

        // If editingId is set, call edit endpoint to update time only
        const editingId = document.getElementById('editingId').value;
        if (editingId) {
            // Send full formData so backend can update movie/day/room/time
            $.ajax({
                url: '<?php echo base_url(); ?>index.php/Qlylich_controller/ajax_editgio/' + editingId,
                type: 'POST',
                dataType: 'json',
                data: formData,
                success: function(response) {
                    console.log('Edit response:', response);
                    if (response && response.success) {
                        showSuccessMessage(response.message || 'Cập nhật lịch chiếu thành công!');
                        bootstrap.Modal.getInstance(document.getElementById('addScheduleModal')).hide();
                        // Clear editingId
                        document.getElementById('editingId').value = '';
                        const currentViewedDate = getCurrentViewedDate();
                        refreshCalendarData(function() {
                            if (currentViewedDate && isScheduleDetailsVisible()) {
                                showScheduleDetails(currentViewedDate);
                            }
                        });
                    } else {
                        showErrorMessage('Lỗi: ' + (response && response.message ? response.message : 'Không thể cập nhật lịch chiếu'));
                    }
                },
                error: function(xhr, status, error) {
                    console.error('Error editing schedule:', error, xhr && xhr.responseText);
                    showErrorMessage('Có lỗi xảy ra khi cập nhật lịch chiếu!');
                },
                complete: function() {
                    saveBtn.disabled = false;
                    saveBtn.innerHTML = originalText;
                }
            });
            return;
        }

        // AJAX call to save schedule (create new)
        $.ajax({
            url: '<?php echo base_url(); ?>index.php/Qlylich_controller/ajax_add_schedule',
            type: 'POST',
            dataType: 'json',
            data: formData,
            success: function(response) {
                console.log('Schedule saved:', response);
                if (response.success) {
                    // Show success message
                    showSuccessMessage('Thêm lịch chiếu thành công !');

                    // Close modal
                    bootstrap.Modal.getInstance(document.getElementById('addScheduleModal')).hide();

                    // Store the current viewed date before refreshing
                    const currentViewedDate = getCurrentViewedDate();

                    // Refresh calendar data
                    refreshCalendarData(function() {
                        // After calendar refresh, check if we need to refresh schedule details
                        if (currentViewedDate && isScheduleDetailsVisible()) {
                            showScheduleDetails(currentViewedDate);
                        }
                    });
                } else {
                    showErrorMessage('Lỗi: ' + (response.message || 'Không thể thêm lịch chiếu'));
                }
            },
            error: function(xhr, status, error) {
                console.error('Error saving schedule:', error);
                showErrorMessage('Có lỗi xảy ra khi thêm lịch chiếu!');
            },
            complete: function() {
                // Re-enable the save button
                saveBtn.disabled = false;
                saveBtn.innerHTML = originalText;
            }
        });
    }
        // Expose functions to global scope so other handlers can call them
        window.refreshCalendarData = refreshCalendarData;
        window.showScheduleDetails = showScheduleDetails;
        window.loadMovies = loadMovies;
    }

    // Helper functions for user feedback and state management
    function showSuccessMessage(message) {
        // Create and show a success toast/notification
        const toast = document.createElement('div');
        toast.className = 'alert alert-success fade show position-fixed';
        toast.style.cssText = 'top: 20px; right: 20px; z-index: 9999; min-width: 300px;';
        toast.innerHTML = `
            <i class="fas fa-check-circle"></i> ${message}
        `;
        document.body.appendChild(toast);

        // Auto remove after 3 seconds
        setTimeout(function() {
            if (toast.parentNode) {
                toast.remove();
            }
        }, 3000);
    }

    function showErrorMessage(message) {
        // Create and show an error toast/notification
        const toast = document.createElement('div');
        toast.className = 'alert alert-danger fade show position-fixed';
        toast.style.cssText = 'top: 20px; right: 20px; z-index: 9999; min-width: 300px;';
        toast.innerHTML = `
            <i class="fas fa-exclamation-triangle"></i> ${message}
        `;
        document.body.appendChild(toast);

        // Auto remove after 5 seconds
        setTimeout(function() {
            if (toast.parentNode) {
                toast.remove();
            }
        }, 5000);
    }

    function getCurrentViewedDate() {
        // Get the date from the data attribute we set when showing schedule details
        const scheduleDetails = document.getElementById('scheduleDetails');
        return scheduleDetails ? scheduleDetails.getAttribute('data-current-date') : null;
    }

    function isScheduleDetailsVisible() {
        const scheduleDetails = document.getElementById('scheduleDetails');
        return scheduleDetails && !scheduleDetails.innerHTML.includes('Chọn một ngày để xem chi tiết');
    }

    // Global functions for schedule management
    window.editSchedule = function(btnOrId) {
        try {
            // Accept either element (this) or id
            let el = null;
            if (typeof btnOrId === 'object' && btnOrId !== null) {
                el = btnOrId;
            } else {
                el = document.querySelector('[data-id="' + btnOrId + '"]');
            }
            if (!el) {
                console.warn('Could not find schedule element for edit', btnOrId);
                return;
            }

            const parent = el.closest('.schedule-item') || el;
            const id = parent.getAttribute('data-id');
            const day = parent.getAttribute('data-day');
            const time = parent.getAttribute('data-time');
            const id_movie = parent.getAttribute('data-id_movie');
            const id_phong = parent.getAttribute('data-id_phong');

            // Open modal in edit mode
            document.getElementById('editingId').value = id;
            document.getElementById('scheduleForm').reset();
            document.getElementById('scheduleDate').value = day || '';
            document.getElementById('scheduleRoom').value = id_phong || '';

            // Set hour/minute selects from time
            if (time && time.indexOf(':') > -1) {
                const parts = time.split(':');
                const hh = parts[0].padStart(2,'0');
                const mm = parts[1].padStart(2,'0');
                const hourEl = document.getElementById('scheduleHour');
                const minuteEl = document.getElementById('scheduleMinute');
                if (hourEl) hourEl.value = hh;
                if (minuteEl) minuteEl.value = mm;
            }

            // Load movies and select the current movie after loading
            loadMovies(function() {
                const movieEl = document.getElementById('scheduleMovie');
                if (movieEl && id_movie) {
                    movieEl.value = id_movie;
                }
            });

            // Show modal
            const modal = new bootstrap.Modal(document.getElementById('addScheduleModal'));
            modal.show();
        } catch (e) {
            console.error('editSchedule error', e);
        }
    };

    window.deleteSchedule = function(btnOrId) {
        try {
            let id = null;
            if (typeof btnOrId === 'object' && btnOrId !== null) {
                const parent = btnOrId.closest('.schedule-item') || btnOrId;
                id = parent.getAttribute('data-id');
            } else {
                id = btnOrId;
            }
            if (!id) {
                console.warn('Could not determine id to delete', btnOrId);
                return;
            }

            if (!confirm('Bạn có chắc chắn muốn xóa lịch chiếu này?')) return;

            $.ajax({
                url: '<?php echo base_url(); ?>index.php/Qlylich_controller/ajax_xoagio/' + id,
                type: 'POST',
                dataType: 'json',
                success: function(response) {
                    if (response && response.success) {
                        showSuccessMessage(response.message || 'Xóa lịch chiếu thành công!');
                        // Refresh calendar and details
                        refreshCalendarData(function() {
                            const currentViewedDate = getCurrentViewedDate();
                            if (currentViewedDate && isScheduleDetailsVisible()) {
                                showScheduleDetails(currentViewedDate);
                            }
                        });
                    } else {
                        showErrorMessage(response && response.message ? response.message : 'Có lỗi khi xóa lịch chiếu');
                    }
                },
                error: function(xhr, status, error) {
                    console.error('Error deleting schedule:', error, xhr && xhr.responseText);
                    showErrorMessage('Có lỗi khi xóa lịch chiếu');
                }
            });
        } catch (e) {
            console.error('deleteSchedule error', e);
        }
    };

// Initialize after jQuery and Bootstrap are loaded
function checkDependencies() {
    if (typeof jQuery !== 'undefined' && typeof bootstrap !== 'undefined') {
        $(document).ready(function() {
            initCalendar();
            makeModalsDraggable();
        });
        return true;
    }
    return false;
}

// Make modals draggable using pure JavaScript
function makeModalsDraggable() {
    console.log('Making modals draggable...');

    // Use event delegation for better performance and to handle dynamically created modals
    document.addEventListener('mousedown', function(e) {
        // Check if clicked on modal header
        if (e.target.closest('.modal-header')) {
            const modalHeader = e.target.closest('.modal-header');
            const modal = modalHeader.closest('.modal');
            const modalDialog = modal.querySelector('.modal-dialog');

            if (!modalDialog) return;

            console.log('Starting modal drag');

            // Add dragging class
            modal.classList.add('dragging');

            let startX = e.clientX;
            let startY = e.clientY;
            const rect = modalDialog.getBoundingClientRect();
            let initialX = rect.left;
            let initialY = rect.top;

                    // Preserve original dimensions before changing position
                    const originalWidth = modalDialog.offsetWidth;
                    const originalHeight = modalDialog.offsetHeight;

                    // Set initial position with preserved dimensions
                    modalDialog.style.position = 'fixed';
                    modalDialog.style.left = initialX + 'px';
                    modalDialog.style.top = initialY + 'px';
                    modalDialog.style.width = originalWidth + 'px';
                    modalDialog.style.minWidth = originalWidth + 'px';
                    modalDialog.style.height = originalHeight + 'px';
                    modalDialog.style.minHeight = originalHeight + 'px';
                    modalDialog.style.transform = 'none';
                    modalDialog.style.margin = '0';
                    modalDialog.style.maxWidth = 'none'; // Remove Bootstrap max-width constraint

            function moveModal(e) {
                const deltaX = e.clientX - startX;
                const deltaY = e.clientY - startY;

                let newX = initialX + deltaX;
                let newY = initialY + deltaY;

                // Constrain to window bounds with some padding
                const padding = 10;
                const maxX = window.innerWidth - modalDialog.offsetWidth - padding;
                const maxY = window.innerHeight - modalDialog.offsetHeight - padding;

                newX = Math.max(padding, Math.min(newX, maxX));
                newY = Math.max(padding, Math.min(newY, maxY));

                modalDialog.style.left = newX + 'px';
                modalDialog.style.top = newY + 'px';
            }

            function stopDrag() {
                console.log('Modal drag completed');
                modal.classList.remove('dragging');
                // Note: We keep the position and dimensions for visual feedback
                // They will be reset when modal is hidden
                document.removeEventListener('mousemove', moveModal);
                document.removeEventListener('mouseup', stopDrag);
            }

            document.addEventListener('mousemove', moveModal);
            document.addEventListener('mouseup', stopDrag);

            // Prevent default behavior
            e.preventDefault();
        }
    });

    // Reset modal position and dimensions when hidden
    document.addEventListener('hidden.bs.modal', function(e) {
        const modal = e.target;
        const modalDialog = modal.querySelector('.modal-dialog');
        if (modalDialog) {
            modalDialog.style.position = '';
            modalDialog.style.left = '';
            modalDialog.style.top = '';
            modalDialog.style.width = '';
            modalDialog.style.minWidth = '';
            modalDialog.style.height = '';
            modalDialog.style.minHeight = '';
            modalDialog.style.transform = '';
            modalDialog.style.margin = '';
            modalDialog.style.maxWidth = '';
            modal.classList.remove('dragging');
        }
    });

    // Add cursor style to modal headers
    const modalHeaders = document.querySelectorAll('.modal-header');
    modalHeaders.forEach(header => {
        header.style.cursor = 'move';
        header.style.userSelect = 'none';
    });

    console.log('Modal drag functionality initialized');
}

// Check immediately
if (!checkDependencies()) {
    // Check periodically
    var checkDeps = setInterval(function() {
        if (checkDependencies()) {
            clearInterval(checkDeps);
        }
    }, 100);
}
</script>

<style>
.calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 2px;
    background: #f8f9fa;
    border: 1px solid #dee2e6;
    border-radius: 0.375rem;
    overflow: hidden;
}

.calendar-day-header {
    background: #e9ecef;
    padding: 8px;
    text-align: center;
    font-weight: bold;
    color: #495057;
    border-bottom: 1px solid #dee2e6;
}

.calendar-day {
    background: white;
    min-height: 100px;
    padding: 4px;
    border: 1px solid #dee2e6;
    position: relative;
    cursor: pointer;
    transition: background-color 0.2s;
}

.calendar-day:hover {
    background-color: #f8f9fa;
}

.calendar-day.current-month {
    background-color: white;
}

.calendar-day.other-month {
    background-color: #f8f9fa;
    color: #adb5bd;
}

.calendar-day.has-schedule {
    background-color: #d1ecf1;
    border-color: #17a2b8;
}

.calendar-day.has-schedule:hover {
    background-color: #bee5eb;
}

.calendar-day.selected {
    outline: 3px solid rgba(0, 123, 255, 0.6);
    box-shadow: 0 4px 10px rgba(0,0,0,0.08);
    background-color: #cfe9ff;
}

.day-number {
    font-weight: bold;
    margin-bottom: 4px;
}

.day-schedules {
    font-size: 11px;
}

.room-schedule {
    padding: 2px 4px;
    margin: 1px 0;
    border-radius: 3px;
    font-size: 10px;
    line-height: 1.2;
}

.room-schedule.room-1 {
    background-color: #007bff;
    color: white;
}

.room-schedule.room-2 {
    background-color: #28a745;
    color: white;
}

.schedule-item {
    background: #f8f9fa;
}

.schedule-item:hover {
    background: #e9ecef;
}

/* Draggable Modal Styles */
.modal-header {
    cursor: move;
    user-select: none;
    transition: none;
}

.modal.dragging .modal-dialog {
    transition: none !important; /* Disable Bootstrap's transform transition when dragging */
}

.modal.dragging {
    user-select: none;
}

/* Ensure modal keeps its size when positioned fixed */
.modal.dragging .modal-dialog {
    box-sizing: border-box !important;
}
</style>

<?php
// Get the content
$content = ob_get_clean();

// Load the layout
$this->load->view('admin_layout', array(
    'page_title' => $page_title,
    'page_breadcrumb' => $page_breadcrumb,
    'show_clock' => $show_clock,
    'additional_css' => $additional_css,
    'additional_js' => $additional_js,
    'content' => $content
));
?>
